import { COLUMNS, type RawRow } from "./types"
import { normalizeRows } from "./processo-utils"

// Dados de exemplo "sujos" na MESMA estrutura da planilha real,
// para validar o layout sem depender do fetch.
const RAW_MOCK: RawRow[] = [
  {
    [COLUMNS.pae]: "E-2026/2181578",
    [COLUMNS.objeto]: "Aquisição de material de combate a incêndio (mangueiras e esguichos)",
    [COLUMNS.taxaProg]: "75%",
    [COLUMNS.observacao]: "Processo prioritário. Aguardando parecer da assessoria jurídica.",
    [COLUMNS.setorDemandante]: "DIRETORIA DE LOGÍSTICA",
    [COLUMNS.naturezaDespesa]: "CONSUMO",
    [COLUMNS.fonte]: "TESOURO",
    [COLUMNS.vPca]: "R$ 218.780,23",
    [COLUMNS.vEstimado]: "R$ 210.500,00",
    [COLUMNS.vHomologado]: "R$ 198.900,00",
    [COLUMNS.vExecutado]: "",
    [COLUMNS.ritoProcessual]: "PREGÃO ELETRÔNICO",
    [COLUMNS.faseProcesso]: "EXTERNA",
    [COLUMNS.subfaseProcesso]: "8 PAGAMENTO",
    [COLUMNS.setorAtual]: "CBM > DIRETORIA DE LOGÍSTICA > SEÇÃO DE COMPRAS",
    [COLUMNS.andamento]: "AJUSTAR/ AJUSTADO",
    [COLUMNS.ultimaTramitacao]: "12/08/2026",
    [COLUMNS.diasUltimoAndamento]: "7",
    [COLUMNS.dataEntrada]: "03/02/2026",
    [COLUMNS.tempoTotalDias]: "190",
    [COLUMNS.previsaoPca]: "SIM",
  },
  {
    [COLUMNS.pae]: "E-2026/2181902",
    [COLUMNS.objeto]: "Contratação de serviço de manutenção preventiva de viaturas",
    [COLUMNS.taxaProg]: "40%",
    [COLUMNS.observacao]: "Aguardando cotação de mercado.",
    [COLUMNS.setorDemandante]: "DIRETORIA DE APOIO LOGÍSTICO",
    [COLUMNS.naturezaDespesa]: "SERVIÇO",
    [COLUMNS.fonte]: "FEBOM",
    [COLUMNS.vPca]: "R$ 1.250.000,00",
    [COLUMNS.vEstimado]: "R$ 1.180.400,00",
    [COLUMNS.vHomologado]: "",
    [COLUMNS.vExecutado]: "",
    [COLUMNS.ritoProcessual]: "PREGÃO ELETRÔNICO",
    [COLUMNS.faseProcesso]: "INTERNA",
    [COLUMNS.subfaseProcesso]: "1 INSTRUÇÃO",
    [COLUMNS.setorAtual]: "CBM > DIRETORIA DE APOIO LOGÍSTICO > SEÇÃO DE TRANSPORTES",
    [COLUMNS.andamento]: "INSTRUIR PROCESSO",
    [COLUMNS.ultimaTramitacao]: "22/07/2026",
    [COLUMNS.diasUltimoAndamento]: "42",
    [COLUMNS.dataEntrada]: "15/06/2026",
    [COLUMNS.tempoTotalDias]: "66",
    [COLUMNS.previsaoPca]: "NÃO",
  },
  {
    [COLUMNS.pae]: "E-2026/2179431",
    [COLUMNS.objeto]: "Aquisição de equipamentos de proteção individual (EPI)",
    [COLUMNS.taxaProg]: "100%",
    [COLUMNS.observacao]: "Entrega concluída e liquidada.",
    [COLUMNS.setorDemandante]: "COMANDO GERAL",
    [COLUMNS.naturezaDespesa]: "CONSUMO E PERMANENTE",
    [COLUMNS.fonte]: "TESOURO",
    [COLUMNS.vPca]: "R$ 540.000,00",
    [COLUMNS.vEstimado]: "R$ 532.100,00",
    [COLUMNS.vHomologado]: "R$ 528.700,00",
    [COLUMNS.vExecutado]: "R$ 528.700,00",
    [COLUMNS.ritoProcessual]: "ADESÃO À ATA",
    [COLUMNS.faseProcesso]: "EXTERNA",
    [COLUMNS.subfaseProcesso]: "9 FINALIZADO",
    [COLUMNS.setorAtual]: "CBM > COMANDO GERAL > PROTOCOLO",
    [COLUMNS.andamento]: "FINALIZADO",
    [COLUMNS.ultimaTramitacao]: "30/06/2026",
    [COLUMNS.diasUltimoAndamento]: "3",
    [COLUMNS.dataEntrada]: "10/01/2026",
    [COLUMNS.tempoTotalDias]: "171",
    [COLUMNS.previsaoPca]: "SIM",
  },
  {
    [COLUMNS.pae]: "E-2026/2175220",
    [COLUMNS.objeto]: "Reforma da sede do 2º Grupamento Bombeiro Militar",
    [COLUMNS.taxaProg]: "-%",
    [COLUMNS.observacao]: "ARQUIVADO - falta de disponibilidade orçamentária.",
    [COLUMNS.setorDemandante]: "DIRETORIA DE ENGENHARIA",
    [COLUMNS.naturezaDespesa]: "SERVIÇO",
    [COLUMNS.fonte]: "A DEFINIR",
    [COLUMNS.vPca]: "R$ 3.400.000,00",
    [COLUMNS.vEstimado]: "R$ 3.380.000,00",
    [COLUMNS.vHomologado]: "",
    [COLUMNS.vExecutado]: "",
    [COLUMNS.ritoProcessual]: "DISPENSA",
    [COLUMNS.faseProcesso]: "",
    [COLUMNS.subfaseProcesso]: "2 ANÁLISE",
    [COLUMNS.setorAtual]: "CBM > DIRETORIA DE ENGENHARIA",
    [COLUMNS.andamento]: "ARQUIVADO",
    [COLUMNS.ultimaTramitacao]: "05/05/2026",
    [COLUMNS.diasUltimoAndamento]: "98",
    [COLUMNS.dataEntrada]: "20/03/2026",
    [COLUMNS.tempoTotalDias]: "46",
    [COLUMNS.previsaoPca]: "NÃO",
  },
  {
    [COLUMNS.pae]: "E-2026/2183310",
    [COLUMNS.objeto]: "Aquisição de viaturas de resgate 4x4",
    [COLUMNS.taxaProg]: "55%",
    [COLUMNS.observacao]: "Impugnação ao edital em análise.",
    [COLUMNS.setorDemandante]: "DIRETORIA DE LOGÍSTICA",
    [COLUMNS.naturezaDespesa]: "PERMANENTE",
    [COLUMNS.fonte]: "SRP",
    [COLUMNS.vPca]: "R$ 4.800.000,00",
    [COLUMNS.vEstimado]: "R$ 4.750.000,00",
    [COLUMNS.vHomologado]: "",
    [COLUMNS.vExecutado]: "",
    [COLUMNS.ritoProcessual]: "PREGÃO ELETRÔNICO",
    [COLUMNS.faseProcesso]: "EXTERNA",
    [COLUMNS.subfaseProcesso]: "6 LICITAÇÃO",
    [COLUMNS.setorAtual]: "CBM > DIRETORIA DE LOGÍSTICA > COMISSÃO DE LICITAÇÃO",
    [COLUMNS.andamento]: "AGUARDANDO JULGAMENTO",
    [COLUMNS.ultimaTramitacao]: "18/08/2026",
    [COLUMNS.diasUltimoAndamento]: "18",
    [COLUMNS.dataEntrada]: "02/04/2026",
    [COLUMNS.tempoTotalDias]: "138",
    [COLUMNS.previsaoPca]: "SIM",
  },
  {
    [COLUMNS.pae]: "E-2026/2184001",
    [COLUMNS.objeto]: "Contratação de serviço de telefonia móvel corporativa",
    [COLUMNS.taxaProg]: "20%",
    [COLUMNS.observacao]: "",
    [COLUMNS.setorDemandante]: "DIRETORIA DE TECNOLOGIA",
    [COLUMNS.naturezaDespesa]: "SERVIÇO",
    [COLUMNS.fonte]: "TESOURO",
    [COLUMNS.vPca]: "R$ 96.000,00",
    [COLUMNS.vEstimado]: "R$ 92.400,00",
    [COLUMNS.vHomologado]: "",
    [COLUMNS.vExecutado]: "",
    [COLUMNS.ritoProcessual]: "DISPENSA POR VALOR",
    [COLUMNS.faseProcesso]: "INTERNA",
    [COLUMNS.subfaseProcesso]: "1 INSTRUÇÃO",
    [COLUMNS.setorAtual]: "CBM > DIRETORIA DE TECNOLOGIA > SEÇÃO DE CONTRATOS",
    [COLUMNS.andamento]: "INSTRUIR PROCESSO",
    [COLUMNS.ultimaTramitacao]: "01/08/2026",
    [COLUMNS.diasUltimoAndamento]: "35",
    [COLUMNS.dataEntrada]: "12/07/2026",
    [COLUMNS.tempoTotalDias]: "38",
    [COLUMNS.previsaoPca]: "NÃO",
  },
  {
    [COLUMNS.pae]: "E-2026/2182740",
    [COLUMNS.objeto]: "Aquisição de mobiliário para quartel central",
    [COLUMNS.taxaProg]: "90%",
    [COLUMNS.observacao]: "Homologado, aguardando emissão de empenho.",
    [COLUMNS.setorDemandante]: "COMANDO GERAL",
    [COLUMNS.naturezaDespesa]: "PERMANENTE",
    [COLUMNS.fonte]: "FEBOM",
    [COLUMNS.vPca]: "R$ 315.000,00",
    [COLUMNS.vEstimado]: "R$ 308.200,00",
    [COLUMNS.vHomologado]: "R$ 299.980,00",
    [COLUMNS.vExecutado]: "",
    [COLUMNS.ritoProcessual]: "PREGÃO ELETRÔNICO",
    [COLUMNS.faseProcesso]: "EXTERNA",
    [COLUMNS.subfaseProcesso]: "7 CONTRATAÇÃO",
    [COLUMNS.setorAtual]: "CBM > COMANDO GERAL > SEÇÃO DE ORÇAMENTO",
    [COLUMNS.andamento]: "EMITIR EMPENHO",
    [COLUMNS.ultimaTramitacao]: "16/08/2026",
    [COLUMNS.diasUltimoAndamento]: "4",
    [COLUMNS.dataEntrada]: "22/01/2026",
    [COLUMNS.tempoTotalDias]: "205",
    [COLUMNS.previsaoPca]: "SIM",
  },
  {
    [COLUMNS.pae]: "E-2026/2180115",
    [COLUMNS.objeto]: "Contratação de curso de capacitação em salvamento aquático",
    [COLUMNS.taxaProg]: "30%",
    [COLUMNS.observacao]: "Termo de referência em elaboração.",
    [COLUMNS.setorDemandante]: "DIRETORIA DE ENSINO",
    [COLUMNS.naturezaDespesa]: "SERVIÇO",
    [COLUMNS.fonte]: "TED MPPA",
    [COLUMNS.vPca]: "R$ 72.000,00",
    [COLUMNS.vEstimado]: "R$ 70.000,00",
    [COLUMNS.vHomologado]: "",
    [COLUMNS.vExecutado]: "",
    [COLUMNS.ritoProcessual]: "INEXIGIBILIDADE",
    [COLUMNS.faseProcesso]: "INTERNA",
    [COLUMNS.subfaseProcesso]: "2 ANÁLISE",
    [COLUMNS.setorAtual]: "CBM > DIRETORIA DE ENSINO > COORDENAÇÃO PEDAGÓGICA",
    [COLUMNS.andamento]: "ANALISAR TR",
    [COLUMNS.ultimaTramitacao]: "10/08/2026",
    [COLUMNS.diasUltimoAndamento]: "10",
    [COLUMNS.dataEntrada]: "28/06/2026",
    [COLUMNS.tempoTotalDias]: "53",
    [COLUMNS.previsaoPca]: "SIM",
  },
  {
    [COLUMNS.pae]: "E-2026/2178009",
    [COLUMNS.objeto]: "Prorrogação de contrato de vigilância armada",
    [COLUMNS.taxaProg]: "60%",
    [COLUMNS.observacao]: "Renovação anual contratual.",
    [COLUMNS.setorDemandante]: "DIRETORIA DE APOIO LOGÍSTICO",
    [COLUMNS.naturezaDespesa]: "SERVIÇO",
    [COLUMNS.fonte]: "TESOURO",
    [COLUMNS.vPca]: "R$ 890.000,00",
    [COLUMNS.vEstimado]: "R$ 885.300,00",
    [COLUMNS.vHomologado]: "R$ 885.300,00",
    [COLUMNS.vExecutado]: "R$ 220.000,00",
    [COLUMNS.ritoProcessual]: "PRORROGAÇÃO",
    [COLUMNS.faseProcesso]: "EXTERNA",
    [COLUMNS.subfaseProcesso]: "8 PAGAMENTO",
    [COLUMNS.setorAtual]: "CBM > DIRETORIA DE APOIO LOGÍSTICO > SEÇÃO DE CONTRATOS",
    [COLUMNS.andamento]: "ACOMPANHAR EXECUÇÃO",
    [COLUMNS.ultimaTramitacao]: "14/08/2026",
    [COLUMNS.diasUltimoAndamento]: "6",
    [COLUMNS.dataEntrada]: "05/01/2026",
    [COLUMNS.tempoTotalDias]: "222",
    [COLUMNS.previsaoPca]: "SIM",
  },
  {
    [COLUMNS.pae]: "E-2026/2185550",
    [COLUMNS.objeto]: "Aquisição de kits de primeiros socorros",
    [COLUMNS.taxaProg]: "15%",
    [COLUMNS.observacao]: "Demanda urgente do interior.",
    [COLUMNS.setorDemandante]: "DIRETORIA DE SAÚDE",
    [COLUMNS.naturezaDespesa]: "CONSUMO",
    [COLUMNS.fonte]: "NOA",
    [COLUMNS.vPca]: "R$ 45.000,00",
    [COLUMNS.vEstimado]: "R$ 43.900,00",
    [COLUMNS.vHomologado]: "",
    [COLUMNS.vExecutado]: "",
    [COLUMNS.ritoProcessual]: "DISPENSA POR VALOR",
    [COLUMNS.faseProcesso]: "INTERNA",
    [COLUMNS.subfaseProcesso]: "1 INSTRUÇÃO",
    [COLUMNS.setorAtual]: "CBM > DIRETORIA DE SAÚDE > ALMOXARIFADO",
    [COLUMNS.andamento]: "INSTRUIR PROCESSO",
    [COLUMNS.ultimaTramitacao]: "19/08",
    [COLUMNS.diasUltimoAndamento]: "45",
    [COLUMNS.dataEntrada]: "",
    [COLUMNS.tempoTotalDias]: "",
    [COLUMNS.previsaoPca]: "NÃO",
  },
  {
    [COLUMNS.pae]: "E-2026/2186221",
    [COLUMNS.objeto]: "Registro de preços para aquisição de combustível",
    [COLUMNS.taxaProg]: "80%",
    [COLUMNS.observacao]: "Ata gerenciada pelo CBMPA.",
    [COLUMNS.setorDemandante]: "DIRETORIA DE LOGÍSTICA",
    [COLUMNS.naturezaDespesa]: "CONSUMO",
    [COLUMNS.fonte]: "PREGÃO ELETRÔNICO",
    [COLUMNS.vPca]: "R$ 2.100.000,00",
    [COLUMNS.vEstimado]: "R$ 2.050.000,00",
    [COLUMNS.vHomologado]: "R$ 1.980.000,00",
    [COLUMNS.vExecutado]: "R$ 640.000,00",
    [COLUMNS.ritoProcessual]: "GERENCIADOR DA ATA",
    [COLUMNS.faseProcesso]: "EXTERNA",
    [COLUMNS.subfaseProcesso]: "8 PAGAMENTO",
    [COLUMNS.setorAtual]: "CBM > DIRETORIA DE LOGÍSTICA > SEÇÃO DE COMPRAS",
    [COLUMNS.andamento]: "ACOMPANHAR EXECUÇÃO",
    [COLUMNS.ultimaTramitacao]: "17/08/2026",
    [COLUMNS.diasUltimoAndamento]: "3",
    [COLUMNS.dataEntrada]: "08/02/2026",
    [COLUMNS.tempoTotalDias]: "191",
    [COLUMNS.previsaoPca]: "SIM",
  },
  {
    [COLUMNS.pae]: "E-2026/2187002",
    [COLUMNS.objeto]: "Reajuste contratual de serviço de limpeza",
    [COLUMNS.taxaProg]: "-%",
    [COLUMNS.observacao]: "Aguardando índice de reajuste (IPCA).",
    [COLUMNS.setorDemandante]: "DIRETORIA DE APOIO LOGÍSTICO",
    [COLUMNS.naturezaDespesa]: "SERVIÇO",
    [COLUMNS.fonte]: "TESOURO",
    [COLUMNS.vPca]: "",
    [COLUMNS.vEstimado]: "R$ 156.000,00",
    [COLUMNS.vHomologado]: "",
    [COLUMNS.vExecutado]: "",
    [COLUMNS.ritoProcessual]: "REAJUSTE",
    [COLUMNS.faseProcesso]: "INTERNA",
    [COLUMNS.subfaseProcesso]: "2 ANÁLISE",
    [COLUMNS.setorAtual]: "CBM > DIRETORIA DE APOIO LOGÍSTICO > SEÇÃO DE CONTRATOS",
    [COLUMNS.andamento]: "ANALISAR REAJUSTE",
    [COLUMNS.ultimaTramitacao]: "25/07/2026",
    [COLUMNS.diasUltimoAndamento]: "26",
    [COLUMNS.dataEntrada]: "18/07/2026",
    [COLUMNS.tempoTotalDias]: "33",
    [COLUMNS.previsaoPca]: "SIM",
  },
  {
    [COLUMNS.pae]: "E-2026/2188120",
    [COLUMNS.objeto]: "Acréscimo de 25% em contrato de fornecimento de gás",
    [COLUMNS.taxaProg]: "50%",
    [COLUMNS.observacao]: "Aditivo quantitativo.",
    [COLUMNS.setorDemandante]: "DIRETORIA DE SAÚDE",
    [COLUMNS.naturezaDespesa]: "CONSUMO",
    [COLUMNS.fonte]: "FEBOM",
    [COLUMNS.vPca]: "R$ 38.500,00",
    [COLUMNS.vEstimado]: "R$ 38.500,00",
    [COLUMNS.vHomologado]: "R$ 38.500,00",
    [COLUMNS.vExecutado]: "",
    [COLUMNS.ritoProcessual]: "ACRÉSCIMO",
    [COLUMNS.faseProcesso]: "INTERNA",
    [COLUMNS.subfaseProcesso]: "7 CONTRATAÇÃO",
    [COLUMNS.setorAtual]: "CBM > DIRETORIA DE SAÚDE > SEÇÃO DE CONTRATOS",
    [COLUMNS.andamento]: "AJUSTAR/ AJUSTADO",
    [COLUMNS.ultimaTramitacao]: "13/08/2026",
    [COLUMNS.diasUltimoAndamento]: "7",
    [COLUMNS.dataEntrada]: "01/07/2026",
    [COLUMNS.tempoTotalDias]: "50",
    [COLUMNS.previsaoPca]: "SIM",
  },
  // Linha totalmente vazia (deve ser ignorada pelo normalizador).
  {
    [COLUMNS.pae]: "",
    [COLUMNS.objeto]: "",
    [COLUMNS.taxaProg]: "",
    [COLUMNS.observacao]: "",
    [COLUMNS.setorDemandante]: "",
    [COLUMNS.naturezaDespesa]: "",
    [COLUMNS.fonte]: "",
    [COLUMNS.vPca]: "",
    [COLUMNS.vEstimado]: "",
    [COLUMNS.vHomologado]: "",
    [COLUMNS.vExecutado]: "",
    [COLUMNS.ritoProcessual]: "",
    [COLUMNS.faseProcesso]: "",
    [COLUMNS.subfaseProcesso]: "",
    [COLUMNS.setorAtual]: "",
    [COLUMNS.andamento]: "",
    [COLUMNS.ultimaTramitacao]: "",
    [COLUMNS.diasUltimoAndamento]: "",
    [COLUMNS.dataEntrada]: "",
    [COLUMNS.tempoTotalDias]: "",
    [COLUMNS.previsaoPca]: "",
  },
]

export const MOCK_PROCESSOS = normalizeRows(RAW_MOCK)
